// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9cJoayFEu6jN2uF-8LVRNz-KKT8Xv_Ug',
    appId: '1:943821563103:web:97da96d18ff88faadab56a',
    messagingSenderId: '943821563103',
    projectId: 'roombookkaro-38438',
    authDomain: 'roombookkaro-38438.firebaseapp.com',
    storageBucket: 'roombookkaro-38438.firebasestorage.app',
    measurementId: 'G-X9ZYFQY5G0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4E9oRhonLH9i6whDgw2UeiAan1iVAR4s',
    appId: '1:943821563103:android:88bee677ddddc5c0dab56a',
    messagingSenderId: '943821563103',
    projectId: 'roombookkaro-38438',
    storageBucket: 'roombookkaro-38438.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsubAmm2Ih4IaWJ7c-tuy-lWxMMDFiqzc',
    appId: '1:943821563103:ios:8dcb0891cd2aa058dab56a',
    messagingSenderId: '943821563103',
    projectId: 'roombookkaro-38438',
    storageBucket: 'roombookkaro-38438.firebasestorage.app',
    androidClientId: '943821563103-sgj9o1isqtk2v0cmu8rag34v7hrlpnhv.apps.googleusercontent.com',
    iosClientId: '943821563103-ppip0tgrpj0nsh9hgg9bkcq02dudrium.apps.googleusercontent.com',
    iosBundleId: 'com.fc.roombookkaroVendor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsubAmm2Ih4IaWJ7c-tuy-lWxMMDFiqzc',
    appId: '1:943821563103:ios:8dcb0891cd2aa058dab56a',
    messagingSenderId: '943821563103',
    projectId: 'roombookkaro-38438',
    storageBucket: 'roombookkaro-38438.firebasestorage.app',
    androidClientId: '943821563103-sgj9o1isqtk2v0cmu8rag34v7hrlpnhv.apps.googleusercontent.com',
    iosClientId: '943821563103-ppip0tgrpj0nsh9hgg9bkcq02dudrium.apps.googleusercontent.com',
    iosBundleId: 'com.fc.roombookkaroVendor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9cJoayFEu6jN2uF-8LVRNz-KKT8Xv_Ug',
    appId: '1:943821563103:web:b6ab1096f98b350cdab56a',
    messagingSenderId: '943821563103',
    projectId: 'roombookkaro-38438',
    authDomain: 'roombookkaro-38438.firebaseapp.com',
    storageBucket: 'roombookkaro-38438.firebasestorage.app',
    measurementId: 'G-XWZK22T317',
  );
}
